name = "emdee"
description = "Performance sequencer for MDs"
version = "0.1.0-dev"

authors = ["Stephen Merrony"]
maintainers = ["Stephen Merrony <merrony@gmail.com>"]
maintainers-logins = ["SMerrony"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = ["performance", "theatre", "midi", "mp3", "soundtrack", "live"]

executables = ["emdee"]

[[depends-on]]
gtkada = "^24.0.0"

[[depends-on]]
ada_toml = "~0.4.0"
