// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed emdee_icon.png
var resourceEmdeeiconPngData []byte
var resourceEmdeeiconPng = &fyne.StaticResource{
	StaticName:    "emdee_icon.png",
	StaticContent: resourceEmdeeiconPngData,
}
